version: "3.9"

services:
  redis:
    image: redis:7.4
    restart: unless-stopped
    ports:
      - "6379:6379"

  feature-service:
    build:
      context: .
      dockerfile: feature-service/Dockerfile
    restart: unless-stopped
    ports:
      - "60000:50051"
    environment:
      - GRPC_PORT=50051
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  candidate-service:
    build:
      context: .
      dockerfile: candidate-service/Dockerfile
    restart: unless-stopped
    ports:
      - "60001:50052"
    environment:
      - GRPC_PORT=50052
      - FEATURE_SERVICE_HOST=feature-service
      - FEATURE_SERVICE_PORT=50051
    depends_on:
      - feature-service
