[project]
name = "gateway-service"
version = "0.1.0"
description = "Gateway service for movie recommendation API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn>=0.32.0",
    "grpcio>=1.76.0",
    "grpcio-tools>=1.76.0",
]

